org.gradle.jvmargs=-Xmx1G

loom.platform = forge
minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.39
yarn_mappings=1.16.5+build.10
forge_version_range=[36,)
loader_version_range=[36,)
parchment_version=2022.03.06

mod_id=esiraoa3extra
mod_name=Esir AoA3 Extra
mod_license=All Rights Reserved
mod_version=1.5.2
mod_group_id=cn.sh1rocu
mod_authors=Sh1roCu
mod_description=